services:
  database:
    image: 'postgres:17.6-alpine'
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./docker-vols/db-data/:/var/lib/postgresql/data/
  
  pgadmin:
    image: elestio/pgadmin:REL-9_8
    ports:
      - ${PGADMIN_PORT}:80
    environment:
        PGADMIN_DEFAULT_EMAIL: test@user.com
        PGADMIN_DEFAULT_PASSWORD: example
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - ./docker-vols/servers.json:/pgadmin/servers.json

networks: 
  postgres-network:
    driver: bridge
